package com.crediline.model;

/**
 * Created by dimer on 8/14/14.
 */
public enum DocumentTemplatePurpose {
    DPK1,
    DPK2,
    DPK_APPENDIX1,
    DPK_APPENDIX2,
    CONTRACT_GUARANTOR1,
    CONTRACT_GUARANTOR2,
    AGREEMENT_1,
    INSURANCE_NOTE1,
    INCOME_ORDER,
    OUTCOME_ORDER,
    ST_CREDITS_LIST_FULL,
    ST_CREDITS_LIST_OVERDUE,
    ST_CREDITS_LIST_BY_OFFICE,
    ST_CREDITS_LIST_BY_STREET,
    ST_CREDITS_LIST_BY_CITY,
    ST_CREDITS_LIST_BY_PERSON,
    CUSTOM_PURPOSE1,
    CUSTOM_PURPOSE2,
    CUSTOM_PURPOSE3,
    CUSTOM_PURPOSE4,
    CUSTOM_PURPOSE5,
    CUSTOM_PURPOSE6,
    CUSTOM_PURPOSE7,
    CUSTOM_PURPOSE8,
    CUSTOM_PURPOSE9,
    CUSTOM_PURPOSE10,
    CUSTOM_PURPOSE21,
    CUSTOM_PURPOSE22,
    CUSTOM_PURPOSE23,
    CUSTOM_PURPOSE24,
    CUSTOM_PURPOSE25,
    CUSTOM_PURPOSE26,
    CUSTOM_PURPOSE27,
    CUSTOM_PURPOSE28,
    CUSTOM_PURPOSE29,
    ERROR
}
